import type { Config } from "tailwindcss";

// Design tokens sourced from kinetic_obsidian/DESIGN.md (ActionX "Kinetic Obsidian" system).
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    screens: {
      xs: "380px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        surface: "#121318",
        "surface-dim": "#121318",
        "surface-bright": "#38393f",
        "surface-container-lowest": "#0d0e13",
        "surface-container-low": "#1a1b21",
        "surface-container": "#1e1f25",
        "surface-container-high": "#292a2f",
        "surface-container-highest": "#34343a",
        "on-surface": "#e3e1e9",
        "on-surface-variant": "#c7c4d8",
        "inverse-surface": "#e3e1e9",
        "inverse-on-surface": "#2f3036",
        outline: "#918fa1",
        "outline-variant": "#464555",
        "surface-tint": "#c3c0ff",
        primary: "#c3c0ff",
        "on-primary": "#1d00a5",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#4d44e3",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        tertiary: "#4edea3",
        "on-tertiary": "#003824",
        "tertiary-container": "#006e4b",
        "on-tertiary-container": "#67f4b7",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        background: "#121318",
        "on-background": "#e3e1e9",
        "surface-variant": "#34343a",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "gutter-tablet": "1.25rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
      },
      fontFamily: {
        display: ["var(--font-geist)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist)", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-geist)", "system-ui", "sans-serif"],
        "headline-sm": ["var(--font-geist)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-geist)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-geist)", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-geist)", "system-ui", "sans-serif"],
        "label-code-lg": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-code-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-metric": ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        display: [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" },
        ],
        "body-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-code-lg": [
          "13px",
          { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "label-code-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "label-metric": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      maxWidth: {
        workspace: "1280px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        shimmer: "shimmer 1.8s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
